import os
import unittest

class TestDataPipeline(unittest.TestCase):
    def test_directory_structure(self):
        """Verify that all required top-level directories are present."""
        for d in ['data', 'src', 'notebooks', 'tests', 'scripts']:
            self.assertTrue(os.path.exists(d), f"Missing directory: {d}")

    def test_data_files(self):
        """Verify that the cleaned data file was generated by Task 1."""
        self.assertTrue(os.path.exists('data/cleaned_reviews.csv'), "Cleaned data file is missing.")

if __name__ == '__main__':
    unittest.main()
