import os
import unittest

# GitHub Actions automatically sets this environment variable to "true"
# during every CI run. We use it to tell the difference between:
#   - a fresh CI checkout, where data/ is intentionally absent (it's
#     excluded via .gitignore, per the project's data-handling policy)
#   - a local development machine, where the scraping/preprocessing
#     pipeline has already been run and the data files genuinely exist
RUNNING_IN_CI = os.environ.get("GITHUB_ACTIONS") == "true"


class TestDataPipeline(unittest.TestCase):
    def test_directory_structure(self):
        """Verify that all required top-level code directories are present.

        "data" is intentionally excluded from this check: it is listed in
        .gitignore and is never committed to GitHub, so it will not exist
        in a fresh CI checkout. This test only verifies the directories
        that are actually tracked in version control.
        """
        for d in ['src', 'notebooks', 'tests', 'scripts']:
            self.assertTrue(os.path.exists(d), f"Missing directory: {d}")

    @unittest.skipIf(
        RUNNING_IN_CI,
        "data/cleaned_reviews.csv is excluded via .gitignore and will not "
        "exist in a fresh CI checkout; this test only runs in local "
        "development environments where the pipeline has already been run.",
    )
    def test_data_files(self):
        """Verify that the cleaned data file was generated by Task 1.

        Skipped in CI - see the skip reason above. Locally, this test
        still genuinely checks that you've run the pipeline and produced
        the expected file.
        """
        self.assertTrue(os.path.exists('data/cleaned_reviews.csv'), "Cleaned data file is missing.")


if __name__ == '__main__':
    unittest.main()